-- ROBOAM SERVICE V12 : SCHEMA COMPLET (V7 + V8 + V9 + V10 + V11). A exécuter UNE fois dans Supabase > SQL Editor.
-- ROBOAM SERVICE V7 : schéma de départ
create table if not exists public.profiles (
 id uuid primary key references auth.users(id) on delete cascade,
 full_name text,
 phone text,
 created_at timestamptz default now()
);

create table if not exists public.categories (
 id bigint generated by default as identity primary key,
 name text unique not null
);

create table if not exists public.products (
 id bigint generated by default as identity primary key,
 category_id bigint references public.categories(id),
 name text not null,
 description text,
 unit text,
 brand text,
 variant text,
 price numeric(12,2) not null default 0,
 stock integer not null default 0,
 active boolean not null default true,
 created_at timestamptz default now()
);

create table if not exists public.orders (
 id bigint generated by default as identity primary key,
 user_id uuid not null references auth.users(id) on delete cascade,
 status text not null default 'reçue',
 total numeric(12,2) not null default 0,
 delivery_address text,
 phone text,
 payment_method text,
 created_at timestamptz default now()
);

create table if not exists public.order_items (
 id bigint generated by default as identity primary key,
 order_id bigint not null references public.orders(id) on delete cascade,
 product_id bigint references public.products(id),
 product_name text not null,
 quantity integer not null,
 unit_price numeric(12,2) not null
);

alter table public.profiles enable row level security;
alter table public.categories enable row level security;
alter table public.products enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;

drop policy if exists "public categories read" on public.categories;
create policy "public categories read" on public.categories for select using (true);
drop policy if exists "public active products read" on public.products;
create policy "public active products read" on public.products for select using (active=true);
drop policy if exists "users own orders read" on public.orders;
create policy "users own orders read" on public.orders for select using (auth.uid()=user_id);
drop policy if exists "users own orders insert" on public.orders;
create policy "users own orders insert" on public.orders for insert with check (auth.uid()=user_id);
drop policy if exists "users own order items read" on public.order_items;
create policy "users own order items read" on public.order_items for select using (
 exists(select 1 from public.orders o where o.id=order_id and o.user_id=auth.uid())
);

-- Crée automatiquement le profil à l'inscription
create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path=public as $$
begin
 insert into public.profiles(id,full_name) values(new.id,new.raw_user_meta_data->>'full_name');
 return new;
end; $$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users
for each row execute procedure public.handle_new_user();
-- V8: panier, commandes, lignes, profils, favoris
alter table public.orders add column if not exists delivery_commune text;
alter table public.orders add column if not exists delivery_quartier text;
alter table public.orders add column if not exists delivery_repere text;

create table if not exists public.favorites(
 user_id uuid references auth.users(id) on delete cascade,
 product_id bigint references public.products(id) on delete cascade,
 created_at timestamptz default now(),
 primary key(user_id,product_id)
);
alter table public.favorites enable row level security;
drop policy if exists "favorites own read" on public.favorites;
create policy "favorites own read" on public.favorites for select using(auth.uid()=user_id);
drop policy if exists "favorites own insert" on public.favorites;
create policy "favorites own insert" on public.favorites for insert with check(auth.uid()=user_id);
drop policy if exists "favorites own delete" on public.favorites;
create policy "favorites own delete" on public.favorites for delete using(auth.uid()=user_id);

-- Lecture des propres lignes de commande
drop policy if exists "users own order items read" on public.order_items;
create policy "users own order items read" on public.order_items for select using(
 exists(select 1 from public.orders o where o.id=order_id and o.user_id=auth.uid())
);
-- Insertion des lignes uniquement pour une commande appartenant à l'utilisateur
drop policy if exists "users own order items insert" on public.order_items;
create policy "users own order items insert" on public.order_items for insert with check(
 exists(select 1 from public.orders o where o.id=order_id and o.user_id=auth.uid())
);
-- V9 ADMIN SECURISE
create table if not exists public.admin_users(
 user_id uuid primary key references auth.users(id) on delete cascade,
 created_at timestamptz default now()
);
alter table public.admin_users enable row level security;

drop policy if exists "admin self read" on public.admin_users;
create policy "admin self read" on public.admin_users
for select using(auth.uid()=user_id);

-- A faire UNE FOIS après avoir créé le compte administrateur :
-- insert into public.admin_users(user_id) values('UUID_DU_COMPTE_ADMIN');

-- Policies administrateur : seul un utilisateur présent dans admin_users peut modifier produits/commandes.
drop policy if exists "admins products insert" on public.products;
create policy "admins products insert" on public.products for insert
with check(exists(select 1 from public.admin_users a where a.user_id=auth.uid()));

drop policy if exists "admins products update" on public.products;
create policy "admins products update" on public.products for update
using(exists(select 1 from public.admin_users a where a.user_id=auth.uid()))
with check(exists(select 1 from public.admin_users a where a.user_id=auth.uid()));

drop policy if exists "admins products delete" on public.products;
create policy "admins products delete" on public.products for delete
using(exists(select 1 from public.admin_users a where a.user_id=auth.uid()));

drop policy if exists "admins orders update" on public.orders;
create policy "admins orders update" on public.orders for update
using(exists(select 1 from public.admin_users a where a.user_id=auth.uid()))
with check(exists(select 1 from public.admin_users a where a.user_id=auth.uid()));

drop policy if exists "admins orders read all" on public.orders;
create policy "admins orders read all" on public.orders for select
using(auth.uid()=user_id or exists(select 1 from public.admin_users a where a.user_id=auth.uid()));
-- ROBOAM SERVICE V10 : photos, favoris et avis
alter table public.products add column if not exists image_url text;
alter table public.products add column if not exists slug text;
alter table public.products add column if not exists rating numeric(2,1) default 0;
alter table public.products add column if not exists review_count integer default 0;

create table if not exists public.product_reviews (
 id bigint generated by default as identity primary key,
 product_id bigint not null references public.products(id) on delete cascade,
 user_id uuid not null references auth.users(id) on delete cascade,
 rating integer not null check (rating between 1 and 5),
 comment text,
 created_at timestamptz default now(),
 unique(product_id,user_id)
);
alter table public.product_reviews enable row level security;
drop policy if exists "reviews public read" on public.product_reviews;
drop policy if exists "reviews own insert" on public.product_reviews;
drop policy if exists "reviews own update" on public.product_reviews;
drop policy if exists "reviews own delete" on public.product_reviews;
create policy "reviews public read" on public.product_reviews for select using (true);
create policy "reviews own insert" on public.product_reviews for insert with check (auth.uid()=user_id);
create policy "reviews own update" on public.product_reviews for update using (auth.uid()=user_id);
create policy "reviews own delete" on public.product_reviews for delete using (auth.uid()=user_id);

create index if not exists product_reviews_product_idx on public.product_reviews(product_id);
create index if not exists products_category_idx on public.products(category_id);
create index if not exists products_active_idx on public.products(active);

insert into public.categories(name) values
('Ciment'),('Tôles'),('Parpaings'),('Fer à béton'),('Peintures'),('Électricité'),('Plomberie'),('Outils'),('Quincaillerie')
on conflict(name) do nothing;

-- Les URLs de photos peuvent être renseignées ensuite dans products.image_url.

-- ROBOAM SERVICE V11 : structure de paiement
alter table public.orders add column if not exists payment_status text not null default 'pending' check (payment_status in ('pending','paid','failed','cancelled','cash_on_delivery'));
alter table public.orders add column if not exists payment_provider text;
alter table public.orders add column if not exists payment_reference text;
alter table public.orders add column if not exists paid_at timestamptz;
alter table public.orders add column if not exists delivery_commune text;
alter table public.orders add column if not exists delivery_quartier text;
alter table public.orders add column if not exists delivery_repere text;

create table if not exists public.payment_transactions (
 id bigint generated by default as identity primary key,
 order_id bigint not null references public.orders(id) on delete cascade,
 user_id uuid not null references auth.users(id) on delete cascade,
 provider text not null check (provider in ('wave','orange_money','mtn_momo','cash')),
 amount numeric(12,2) not null check (amount >= 0),
 currency text not null default 'XOF',
 status text not null default 'pending' check (status in ('pending','paid','failed','cancelled')),
 provider_reference text,
 created_at timestamptz not null default now(),
 paid_at timestamptz
);

alter table public.payment_transactions enable row level security;
drop policy if exists "payments own read" on public.payment_transactions;
drop policy if exists "payments own insert" on public.payment_transactions;
drop policy if exists "admin payments read" on public.payment_transactions;
drop policy if exists "admin payments update" on public.payment_transactions;
create policy "payments own read" on public.payment_transactions for select using (auth.uid()=user_id);
create policy "payments own insert" on public.payment_transactions for insert with check (auth.uid()=user_id);
create policy "admin payments read" on public.payment_transactions for select using (exists(select 1 from public.admin_users where user_id=auth.uid()));
create policy "admin payments update" on public.payment_transactions for update using (exists(select 1 from public.admin_users where user_id=auth.uid()));

create index if not exists payment_transactions_order_idx on public.payment_transactions(order_id);
create index if not exists payment_transactions_provider_ref_idx on public.payment_transactions(provider_reference);

-- IMPORTANT : aucune clé API n'est stockée dans Supabase/public.
-- Les secrets Wave/Orange/MTN doivent rester côté serveur/Edge Function.

-- V12 : l'admin peut lire les lignes de commande et modifier les paiements des commandes
drop policy if exists "admins order items read" on public.order_items;
create policy "admins order items read" on public.order_items for select using (exists(select 1 from public.admin_users a where a.user_id=auth.uid()));
drop policy if exists "admins categories write" on public.categories;
create policy "admins categories write" on public.categories for all using (exists(select 1 from public.admin_users a where a.user_id=auth.uid())) with check (exists(select 1 from public.admin_users a where a.user_id=auth.uid()));
